version: "3"

services:

  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - streamlit
    ports:
      - 8000:80
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf

  streamlit:
    build:
      context: .
      dockerfile: ./docker/streamlit/Dockerfile
    container_name: streamlit
    volumes:
      - ./auth.yaml:/usr/src/app/auth.yaml
    ports:
      - 8501:8501
    env_file:
      - .env
